defaults:
  - fe: defaults
  - _self_

hydra:
  run:
    dir: src/rl_nachi/logs/${basename}/${now:%Y%m%d-%H%M}

position_random: False
posture_random: False
device: cuda

basename: SAC_trainedDCAE

fe_with_init: True
