defaults:
  - fe: defaults
  - rl: defaults
  - _self_

hydra:
  run:
    dir: logs/${basename}/${now:%Y%m%d-%H%M}

position_random: False
posture_random: False
save_anim_num: 10
device: cuda

basename: SAC_trainedDCAE_cl2_o-${rl.obs_dim}_a-${rl.act_dim}

fe_with_init: True
